/*
 * token.h
 *
 *  Created on: 10 oct. 2025
 *      Author: secerdan
 */

#ifndef CONFIG_TOKEN_H_
#define CONFIG_TOKEN_H_

#include "nvm3_generic.h"

extern nvm3_Handle_t *nvm3_defaultHandle;

#define NVM3_USER_REGION 0

#define CREATOR_DEVICE_MOVING_THRESHOLD 0x0000
#define NVM3KEY_DEVICE_MOVING_THRESHOLD (NVM3_USER_REGION | CREATOR_DEVICE_MOVING_THRESHOLD)

#define CREATOR_DEVICE_MOVING_THRESHOLD_DEFAULT 10

#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(MOVING_THRESHOLD, uint8_t, CREATOR_DEVICE_MOVING_THRESHOLD_DEFAULT)
#endif  // DEFINETOKENS

#define CREATOR_DEVICE_BASELINE_WEIGHT 0x0001
#define NVM3KEY_DEVICE_BASELINE_WEIGHT (NVM3_USER_REGION | CREATOR_DEVICE_BASELINE_WEIGHT)

#define CREATOR_DEVICE_BASELINE_WEIGHT_DEFAULT 10

#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(BASELINE_WEIGHT, uint8_t, CREATOR_DEVICE_BASELINE_WEIGHT_DEFAULT)
#endif  // DEFINETOKENS

#define CREATOR_DEVICE_OPEN_TIME 0x0002
#define NVM3KEY_DEVICE_OPEN_TIME (NVM3_USER_REGION | CREATOR_DEVICE_OPEN_TIME)

#define CREATOR_DEVICE_OPEN_TIME_DEFAULT 8

#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(OPEN_TIME, uint8_t, CREATOR_DEVICE_OPEN_TIME_DEFAULT)
#endif

#define CREATOR_DEVICE_CLOSE_TIME 0x0003
#define NVM3KEY_DEVICE_CLOSE_TIME (NVM3_USER_REGION | CREATOR_DEVICE_CLOSE_TIME)

#define CREATOR_DEVICE_CLOSE_TIME_DEFAULT 10

#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(CLOSE_TIME, uint8_t, CREATOR_DEVICE_CLOSE_TIME_DEFAULT)
#endif


#endif /* CONFIG_TOKEN_H_ */
